name: Auto Merge UAT to Main

on:
  push:
    branches:
      - UAT

jobs:
  merge-uat-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request from UAT to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: sync-uat-to-main   # <--- Avoid pushing to 'UAT'
          title: '🚀 Auto Merge: UAT → Main'
          body: 'Auto-sync from UAT to Main'
          commit-message: 'Sync UAT to main'
          delete-branch: true
          labels: automerge

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
